# Generated by Django 6.0.3 on 2026-04-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueentry',
            name='queue_type',
            field=models.CharField(choices=[('lab_reception', 'Lab Reception'), ('lab_doctor', 'Lab Request From Doctor'), ('doctor', 'Doctor'), ('nurse', 'Nurse')], max_length=30),
        ),
    ]
