# Generated by Django 6.0.3 on 2026-04-21 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_labreport_lab_request_labreport_sent_to_doctor_and_more'),
        ('reception', '0004_patient_weight_kg_queueentry_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='test_profile',
            field=models.ForeignKey(blank=True, help_text='Lab service linked to a test profile (e.g., CBC, Urinalysis)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='lab.testprofile'),
        ),
        migrations.AddField(
            model_name='visitservice',
            name='performed',
            field=models.BooleanField(default=False, help_text='Whether this service has been performed'),
        ),
        migrations.AddField(
            model_name='visitservice',
            name='performed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
