# Generated by Django 6.0.3 on 2026-04-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_service_test_profile_visitservice_performed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
