# Generated by Django 5.2.6 on 2026-04-24 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_cashtransaction_expense'),
        ('reception', '0006_patient_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='admin_dashboard.bankaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='mobile_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='admin_dashboard.mobilemoneyaccount'),
        ),
    ]
