# Generated by ChatGPT on 2026-04-25

from django.db import migrations
from decimal import Decimal, InvalidOperation


def _parse_int(value):
    if value is None:
        return None
    if isinstance(value, int):
        return value
    text = str(value).strip()
    if not text:
        return None
    try:
        return int(float(text))
    except (TypeError, ValueError):
        return None


def _parse_decimal(value):
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        return Decimal(text)
    except (TypeError, ValueError, InvalidOperation):
        return None


def _parse_bp(value):
    """
    Accepts "120/80" (string) or dict-like {systolic, diastolic}.
    Returns (sys, dia).
    """
    if value is None:
        return (None, None)
    if isinstance(value, (list, tuple)) and len(value) >= 2:
        return (_parse_int(value[0]), _parse_int(value[1]))
    if isinstance(value, dict):
        return (_parse_int(value.get("systolic")), _parse_int(value.get("diastolic")))
    text = str(value).strip()
    if not text:
        return (None, None)
    if "/" in text:
        left, right = text.split("/", 1)
        return (_parse_int(left), _parse_int(right))
    # Some users store BP as a single number; keep systolic only.
    return (_parse_int(text), None)


def migrate_vitals_to_triage(apps, schema_editor):
    Consultation = apps.get_model("doctor", "Consultation")
    Triage = apps.get_model("reception", "Triage")

    for cons in Consultation.objects.all().iterator():
        vitals = cons.vitals or {}
        if not isinstance(vitals, dict) or not vitals:
            continue

        bp_sys, bp_dia = _parse_bp(
            vitals.get("bp")
            or vitals.get("blood_pressure")
            or vitals.get("bp_reading")
        )

        weight = vitals.get("weight_kg") or vitals.get("weight") or vitals.get("wt")
        temp = vitals.get("temp") or vitals.get("temperature") or vitals.get("temperature_celsius")
        glucose = vitals.get("glucose") or vitals.get("glucose_mg_dl")
        spo2 = vitals.get("spo2") or vitals.get("oxygen_saturation")
        pulse = vitals.get("pr") or vitals.get("pulse")
        rr = vitals.get("rr") or vitals.get("respiratory_rate")

        defaults = {
            "weight_kg": _parse_decimal(weight),
            "bp_systolic": bp_sys or _parse_int(vitals.get("bp_systolic")),
            "bp_diastolic": bp_dia or _parse_int(vitals.get("bp_diastolic")),
            "pulse": _parse_int(pulse),
            "respiratory_rate": _parse_int(rr),
            "temperature_celsius": _parse_decimal(temp),
            "oxygen_saturation": _parse_int(spo2),
            "glucose_mg_dl": _parse_int(glucose),
            "recorded_by": cons.created_by,
            "updated_by": cons.created_by,
        }

        # Only write something meaningful.
        if not any(value is not None for key, value in defaults.items() if key not in {"recorded_by", "updated_by"}):
            continue

        Triage.objects.update_or_create(visit_id=cons.visit_id, defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
        ("reception", "0009_triage"),
    ]

    operations = [
        migrations.RunPython(migrate_vitals_to_triage, migrations.RunPython.noop),
    ]
