# Generated by Django 6.0.3 on 2026-05-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0011_patient_address_patient_date_of_birth_patient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueentry',
            name='queue_type',
            field=models.CharField(choices=[('lab_reception', 'Lab Reception'), ('lab_doctor', 'Lab Request From Doctor'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('reception', 'Reception Queue')], max_length=30),
        ),
    ]
