# Generated by Django 6.0.3 on 2026-05-01 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_prescription_adjustment_reason_and_more'),
        ('reception', '0012_alter_queueentry_queue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='adjustment_days_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visit',
            name='adjustment_origin_prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_visits', to='doctor.prescription'),
        ),
        migrations.AddField(
            model_name='visit',
            name='adjustment_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visit',
            name='adjustment_remaining_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visit',
            name='parent_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_visits', to='reception.visit'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('normal', 'Normal Visit'), ('follow_up', 'Follow-up'), ('adjustment', 'Adjustment Visit (Medication Swap)')], default='normal', max_length=20),
        ),
    ]
