# Generated by Django 6.0.3 on 2026-05-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0013_visit_adjustment_days_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitservice',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether this service has been approved (e.g., for payment) by reception'),
        ),
    ]
