# Generated by Django 6.0.3 on 2026-05-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0014_visitservice_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='visit',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
