# Generated by Django 6.0.3 on 2026-06-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0015_add_whatsapp_number_to_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueentry',
            name='queue_type',
            field=models.CharField(choices=[('lab_reception', 'Lab Reception'), ('lab_doctor', 'Lab Request From Doctor'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('sonographer', 'Sonographer'), ('reception', 'Reception Queue')], max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Laboratory'), ('triage', 'Triage'), ('procedure', 'Procedure'), ('pharmacy', 'Pharmacy'), ('scan', 'Scan / Ultrasound'), ('other', 'Other')], max_length=50),
        ),
    ]
