# Generated by Django 6.0.3 on 2026-06-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0016_alter_queueentry_queue_type_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_per_day',
            field=models.BooleanField(default=False, help_text='If checked, billing this service asks for number of days and multiplies the price (e.g. Nursing Fee, Bed Fee).'),
        ),
    ]
