# Generated by Django 6.0.3 on 2026-08-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0017_add_is_per_day_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Weight at visit (kg)'),
        ),
    ]
