# Generated by Django 5.2.6 on 2026-09-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0019_link_cbc_service_test_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueentry',
            name='queue_type',
            field=models.CharField(choices=[('lab_reception', 'Lab Reception'), ('lab_doctor', 'Lab Request From Doctor'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('sonographer', 'Sonographer'), ('reception', 'Reception Queue'), ('phlebotomy', 'Phlebotomy')], max_length=30),
        ),
    ]
