# Generated by Django 5.2.6 on 2026-09-10 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0021_labtest_servicecategory_specimentype_laborder_and_more'),
        ('reception', '0021_alter_queueentry_queue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='lab_test_next',
            field=models.ForeignKey(blank=True, help_text="Lab module rework: which catalog test this billed service maps to under the new engine. Only used for hospitals with LabSettings.engine='next'; unrelated to `test_profile` above, which the legacy engine still reads.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='lab.labtest'),
        ),
    ]
