# Generated by Django 5.2.6 on 2026-09-10 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0022_remove_labsettings_engine'),
        ('reception', '0022_service_lab_test_next'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='lab_test_next',
            field=models.ForeignKey(blank=True, help_text='Which lab.LabTest this billed service maps to. Required for the service to be picked up by the lab queue; unrelated to `test_profile` above, which only the historical report archive still reads.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='lab.labtest'),
        ),
    ]
