# Generated by Django 6.0.3 on 2026-09-17 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0024_service_lab_tests_next_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitservice',
            name='external_requester_facility',
            field=models.CharField(blank=True, help_text="Set when requested_by_type is external_doctor — the referring doctor's facility.", max_length=150),
        ),
        migrations.AddField(
            model_name='visitservice',
            name='external_requester_name',
            field=models.CharField(blank=True, help_text="Set when requested_by_type is external_doctor — the referring doctor's name.", max_length=150),
        ),
        migrations.AddField(
            model_name='visitservice',
            name='requested_by_type',
            field=models.CharField(blank=True, choices=[('self', 'Self-Requested'), ('internal_doctor', 'Doctor (This Facility)'), ('external_doctor', 'Doctor (Outside Facility)')], max_length=20),
        ),
        migrations.AddField(
            model_name='visitservice',
            name='requested_by_user',
            field=models.ForeignKey(blank=True, help_text='Set when requested_by_type is internal_doctor — the doctor who was logged in at request time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
