# Generated by Django 6.0.3 on 2026-09-22 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0025_visitservice_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='package_covers',
            field=models.JSONField(blank=True, default=list, help_text="Only meaningful for category=Package -- which other categories this package grants free access to (e.g. ['consultation', 'lab']). A visit that has this package billed can then be sent to any of these modules, as many times as needed on that same visit, without billing anything extra."),
        ),
        migrations.AddField(
            model_name='visitservice',
            name='covered_by_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitservice',
            name='covering_package',
            field=models.ForeignKey(blank=True, help_text="The package's own VisitService line on this visit that covers this one, when covered_by_package is set.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_services', to='reception.visitservice'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(help_text='Examples: 22YRS, 6MTH, 3WKS, 5DAYS', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Laboratory'), ('triage', 'Triage'), ('procedure', 'Procedure'), ('pharmacy', 'Pharmacy'), ('scan', 'Scan / Ultrasound'), ('package', 'Package'), ('other', 'Other')], max_length=50),
        ),
    ]
