# Generated by Django 6.0.3 on 2026-09-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0026_service_package_covers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='package_covers',
        ),
        migrations.AddField(
            model_name='service',
            name='package_services',
            field=models.ManyToManyField(blank=True, help_text='Only meaningful for category=Package -- the exact service(s) this package includes (e.g. Antenatal -> Consultation, CBC, Urinalysis, Obstetric Ultrasound). A visit with this package billed can be sent for any of these specific services, without billing anything extra for them -- services not on this list still bill normally even if their category matches.', related_name='included_in_packages', to='reception.service'),
        ),
    ]
