# Generated by Django 6.0.3 on 2026-09-23 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0027_remove_service_package_covers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='package_source',
            field=models.ForeignKey(blank=True, help_text='The specific package purchase VisitService line (on an earlier, completed and fully paid visit) being reused on this visit, without re-billing it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reused_by_visits', to='reception.visitservice'),
        ),
        migrations.AddField(
            model_name='visitservice',
            name='package_expires_on',
            field=models.DateField(blank=True, help_text="Only meaningful when this line's service is category=Package -- optional expiry captured at purchase time. Once set and past, this package can no longer be reused on a new visit.", null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('normal', 'Normal Visit'), ('follow_up', 'Follow-up'), ('adjustment', 'Adjustment Visit (Medication Swap)'), ('package_visit', 'Package Visit')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitservice',
            name='covering_package',
            field=models.ForeignKey(blank=True, help_text="The package's own VisitService line (this visit or an earlier one) that covers this one, when covered_by_package is set.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_services', to='reception.visitservice'),
        ),
    ]
