# Generated by Django 6.0.3 on 2026-09-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0028_visit_package_source_visitservice_package_expires_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='max_visits',
            field=models.PositiveIntegerField(blank=True, help_text='Only meaningful for category=Package -- maximum total visits this package covers, counting the purchase visit itself as visit 1. Leave blank for no limit.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='validity_months',
            field=models.PositiveIntegerField(blank=True, help_text='Only meaningful for category=Package -- how many months after purchase this package stays valid for reuse. Leave blank for no expiry.', null=True),
        ),
    ]
