# Generated by Django 6.0.3 on 2026-09-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0018_inventorytransaction_batch_breakdown'),
        ('reception', '0029_service_max_visits_service_validity_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='package_drugs',
            field=models.ManyToManyField(blank=True, help_text='Only meaningful for category=Package -- specific pharmacy drug(s) this package includes, free for whatever quantity/duration the doctor prescribes. Drugs not on this list still bill normally.', related_name='included_in_packages', to='admin_dashboard.inventoryitem'),
        ),
    ]
