# Generated by Django 6.0.3 on 2026-10-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0030_service_package_drugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='specialty',
            field=models.CharField(choices=[('general', 'General'), ('ophthalmology', 'Ophthalmology (eye)'), ('dentistry', 'Dentistry (coming soon)')], default='general', help_text='For consultation services: which exam the doctor fills in for this visit.', max_length=20),
        ),
    ]
