# Generated by Django 6.0.3 on 2026-10-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0031_service_specialty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="triage",
            name="glucose_mg_dl",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
