# Generated by Django 6.0.3 on 2026-06-02 09:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_default_module_groups'),
        ('doctor', '0008_add_nursing_managed_to_prescription'),
        ('nurse', '0001_initial'),
        ('reception', '0015_add_whatsapp_number_to_visit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('discharged', 'Discharged')], default='active', max_length=20)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_notes', models.TextField(blank=True)),
                ('admitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_admissions_started', to=settings.AUTH_USER_MODEL)),
                ('discharged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_discharges', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_admissions', to='accounts.hospital')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_admission', to='reception.visit')),
            ],
            options={
                'ordering': ['-admitted_at'],
            },
        ),
        migrations.CreateModel(
            name='NursingCareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doses_planned', models.PositiveIntegerField()),
                ('per_dose_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=255)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_items', to='nurse.nursingadmission')),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_care_item', to='doctor.prescription')),
                ('stopped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stopped_care_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NursingDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administered_at', models.DateTimeField(auto_now_add=True)),
                ('quantity_given', models.DecimalField(decimal_places=4, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_doses_given', to=settings.AUTH_USER_MODEL)),
                ('care_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='nurse.nursingcareitem')),
            ],
            options={
                'ordering': ['administered_at'],
            },
        ),
    ]
