# Generated by Django 6.0.3 on 2026-06-08 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0002_add_nursing_admission_careitem_dose'),
        ('reception', '0016_alter_queueentry_queue_type_alter_service_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('abdominal', 'Abdominal Ultrasound'), ('obstetric', 'Obstetric Ultrasound'), ('pelvic', 'Pelvic Ultrasound'), ('cardiac', 'Cardiac Ultrasound (Echo)'), ('renal', 'Renal Ultrasound'), ('thyroid', 'Thyroid Ultrasound'), ('musculoskeletal', 'Musculoskeletal Ultrasound'), ('other', 'Other')], default='other', max_length=30)),
                ('clinical_indication', models.TextField(blank=True, help_text='Reason for the scan / clinical notes from referring doctor')),
                ('findings', models.TextField(help_text='Detailed scan findings')),
                ('impression', models.TextField(help_text='Summary / conclusion')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Finalized')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sonographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_reports', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_reports', to='reception.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
