# Generated by Django 6.0.3 on 2026-04-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='lab_requests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
