# Generated by Django 6.0.3 on 2026-04-27 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_inventoryitem_category_and_more'),
        ('doctor', '0003_labrequest_notification'),
        ('reception', '0011_patient_address_patient_date_of_birth_patient_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_mg', models.DecimalField(decimal_places=2, help_text='Dose per intake in mg or ml.', max_digits=8)),
                ('frequency_per_day', models.PositiveIntegerField(help_text='How many times per day.')),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('number_of_packs', models.PositiveIntegerField(default=0, editable=False)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('dispensed', models.BooleanField(default=False)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('billing_visit_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='reception.visitservice')),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(limit_choices_to={'category': 'drug'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='admin_dashboard.inventoryitem')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_created', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='reception.visit')),
            ],
            options={
                'ordering': ['-prescribed_at', '-id'],
            },
        ),
    ]
