# Generated by Django 6.0.3 on 2026-04-27 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_inventoryitem_days_covered_per_pack_and_more'),
        ('doctor', '0004_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='admin_dashboard.inventoryitem'),
        ),
    ]
