# Generated by Django 6.0.3 on 2026-04-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_prescription_drug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='dosage_mg',
            field=models.DecimalField(decimal_places=2, help_text='Dose per intake, interpreted from the medicine form.', max_digits=8),
        ),
    ]
