# Generated by Django 6.0.3 on 2026-05-01 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_prescription_dosage_mg'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='adjustment_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prescription',
            name='covered_by_previous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='days_used_before_adjustment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='discontinued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='discontinued_early',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_adjustment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='parent_prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_prescriptions', to='doctor.prescription'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='remaining_days_covered',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
