# Generated by Django 6.0.3 on 2026-06-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_prescription_adjustment_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='nursing_managed',
            field=models.BooleanField(default=False, help_text='If True, this prescription is dispensed dose-by-dose by nurses, not all at once by pharmacy.'),
        ),
    ]
