# Generated by Django 6.0.3 on 2026-09-24 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_add_nursing_managed_to_prescription'),
        ('reception', '0029_service_max_visits_service_validity_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='covered_by_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='covering_package',
            field=models.ForeignKey(blank=True, help_text="The package's own VisitService line (this visit or an earlier reused one) that covers this prescription, when covered_by_package is set.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_prescriptions', to='reception.visitservice'),
        ),
    ]
