# Generated by Django 6.0.3 on 2026-10-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_prescription_covered_by_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='outcome',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('discharged', 'Discharged'), ('referred', 'Referred'), ('admitted', 'Admitted'), ('theatre', 'Sent to Theatre'), ('died', 'Died'), ('review', 'Review Appointment')], default='ongoing', max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='outcome_notes',
            field=models.CharField(blank=True, help_text='Where to, for Referred / Admitted / Sent to Theatre (e.g. Mulago Eye Unit).', max_length=255),
        ),
    ]
