# Generated by Django 6.0.3 on 2026-03-10 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.CharField(help_text='e.g., 22YRS', max_length=20)),
                ('patient_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('sample_date', models.DateField()),
                ('specimen_type', models.CharField(default='BLOOD', max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('attendant_name', models.CharField(blank=True, help_text="Lab attendant's name", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed', models.BooleanField(default=False)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('reference_range', models.CharField(blank=True, help_text='e.g., 23.5-33.7', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(max_length=50)),
                ('lab_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab.labreport')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.testparameter')),
            ],
            options={
                'unique_together': {('lab_report', 'parameter')},
            },
        ),
    ]
