# Generated by Django 6.0.3 on 2026-03-10
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_default_category(apps, schema_editor):
    TestCategory = apps.get_model('lab', 'TestCategory')
    TestParameter = apps.get_model('lab', 'TestParameter')
    default_cat, _ = TestCategory.objects.get_or_create(name='General', defaults={'display_order': 0})
    TestParameter.objects.filter(category__isnull=True).update(category=default_cat)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Test categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='testparameter',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='lab.testcategory'),
        ),
        migrations.AddField(
            model_name='testparameter',
            name='data_type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('option', 'Option List')], default='numeric', max_length=20),
        ),
        migrations.AddField(
            model_name='testparameter',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testparameter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='testparameter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(set_default_category, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='testparameter',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='lab.testcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='testparameter',
            unique_together={('name', 'category')},
        ),
        migrations.AddField(
            model_name='labreport',
            name='attendant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['parameter__category__display_order', 'parameter__display_order']},
        ),
    ]
