# Generated by Django 6.0.3 on 2026-03-10
from django.db import migrations, models
import django.db.models.deletion


def backfill_catalog(apps, schema_editor):
    TestCatalog = apps.get_model('lab', 'TestCatalog')
    TestResult = apps.get_model('lab', 'TestResult')
    for result in TestResult.objects.all():
        name = getattr(result, 'test_name', '').strip() or 'Unspecified'
        unit = getattr(result, 'unit', '')
        catalog, _ = TestCatalog.objects.get_or_create(name=name, defaults={'unit': unit})
        result.test = catalog
        result.save(update_fields=['test'])


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_simple_free_text_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceRangeDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_category', models.CharField(choices=[('neonate', 'Neonate (0-30 days)'), ('infant', 'Infant (1-6 months)'), ('child_1_5', 'Child (1-5 years)'), ('child_6_11', 'Child (6-11 years)'), ('child_12_17', 'Child (12-17 years)'), ('adult', 'Adult (18+ years)')], max_length=20)),
                ('reference_range', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_ranges', to='lab.testcatalog')),
            ],
            options={
                'unique_together': {('test', 'age_category')},
            },
        ),
        migrations.AddField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.testcatalog'),
        ),
        migrations.RunPython(backfill_catalog, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.testcatalog'),
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='test_name',
        ),
    ]
