# Generated by Django 6.0.3 on 2026-04-17 14:29

import django.db.models.deletion
from django.db import migrations, models


def backfill_lab_report_hospital(apps, schema_editor):
    LabReport = apps.get_model('lab', 'LabReport')
    for report in LabReport.objects.select_related('visit', 'attendant').all():
        hospital_id = None
        if getattr(report, 'visit_id', None) and getattr(report.visit, 'hospital_id', None):
            hospital_id = report.visit.hospital_id
        elif getattr(report, 'attendant_id', None) and getattr(report.attendant, 'hospital_id', None):
            hospital_id = report.attendant.hospital_id
        if hospital_id and report.hospital_id != hospital_id:
            report.hospital_id = hospital_id
            report.save(update_fields=['hospital'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('lab', '0008_update_cbc_reference_ranges'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_reports', to='accounts.hospital'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_reports', to='reception.visit'),
        ),
        migrations.RunPython(backfill_lab_report_hospital, migrations.RunPython.noop),
    ]
