# Generated by Django 6.0.3 on 2026-04-20 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_labrequest_notification'),
        ('lab', '0009_labreport_hospital_labreport_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='lab_request',
            field=models.ForeignKey(blank=True, help_text='Link to the original lab request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='doctor.labrequest'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='sent_to_doctor',
            field=models.BooleanField(default=False, help_text='Whether results have been sent to requesting doctor'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='sent_to_doctor_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
