# Generated by Django 6.0.3 on 2026-04-23 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_add_simple_manual_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='source_profile',
            field=models.ForeignKey(blank=True, help_text='Template/profile that created this row (used for removing a whole template block).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='lab.testprofile'),
        ),
        migrations.AlterField(
            model_name='referencerangedefault',
            name='age_category',
            field=models.CharField(choices=[('neonate', 'Neonate (0-30 days)'), ('infant', 'Infant (1-6 months)'), ('child_1_5', 'Child (1-5 years)'), ('child_6_11', 'Child (6-12 years)'), ('adult', 'Adult (13+ years)')], max_length=20),
        ),
    ]
