# Generated by Django 6.0.3 on 2026-04-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_refresh_cbc_profile_ranges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencerangedefault',
            name='age_category',
            field=models.CharField(choices=[('neonate', 'Neonate'), ('child', 'Child'), ('woman', 'Woman'), ('man', 'Man'), ('general', 'General')], max_length=20),
        ),
    ]
