# Generated by Django 6.0.3 on 2026-06-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_alter_referencerangedefault_age_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencerangedefault',
            name='age_category',
            field=models.CharField(choices=[('neonate', 'Neonate (0-30 days)'), ('infant', 'Infant (1-11 months)'), ('child_1_5', 'Child (1-5 years)'), ('child_6_11', 'Child (6-12 years)'), ('adult', 'Adult (13+ years)')], max_length=20),
        ),
    ]
