# Generated by Django 6.0.3 on 2026-08-20 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_lab_consumables_datetime_sample'),
        ('lab', '0019_stool_params_text_input'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='sample_date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='LabConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(default='units', max_length=50)),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Warn when stock falls at or below this level', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_consumables', to='accounts.hospital')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('hospital', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LabConsumableUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='lab.labconsumable')),
                ('lab_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_usages', to='lab.labreport')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
    ]
