# Generated by Django 5.2.6 on 2026-09-10 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_seed_ternah_books_tenant'),
        ('lab', '0020_lab_consumables_datetime_sample'),
        ('reception', '0021_alter_queueentry_queue_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('active_for_ordering', models.BooleanField(default=True)),
                ('result_type', models.CharField(choices=[('free_entry', 'Free Entry'), ('defined_option', 'Defined Option'), ('parameter_panel', 'Parameter Panel'), ('culture', 'Culture & Sensitivity')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'service categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecimenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('pending', 'Pending'), ('sample_collected', 'Sample Collected'), ('in_progress', 'In Progress'), ('entered', 'Results Entered'), ('reviewed', 'Reviewed'), ('released', 'Released')], default='pending', max_length=20)),
                ('priority_routine', models.BooleanField(default=True, help_text='False = Urgent')),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('is_outside_sample', models.BooleanField(default=False)),
                ('outside_source', models.CharField(blank=True, max_length=200)),
                ('collection_notes', models.TextField(blank=True)),
                ('patient_sex', models.CharField(choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=6)),
                ('patient_age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('entry_mode_at_creation', models.CharField(blank=True, choices=[('from_lab', 'From Lab (Phlebotomy intake)'), ('from_reception', 'From Reception (standard)')], max_length=20)),
                ('print_group_id', models.CharField(blank=True, max_length=40)),
                ('legacy_report_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_collections_next', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders_next', to='accounts.hospital')),
                ('visit_service', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lab_order_next', to='reception.visitservice')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='lab.labtest')),
                ('specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.specimentype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('free_entry', 'Free Entry'), ('defined_option', 'Defined Option'), ('parameter_panel', 'Parameter Panel'), ('culture', 'Culture & Sensitivity')], max_length=20)),
                ('free_text', models.TextField(blank=True)),
                ('chosen_option', models.CharField(blank=True, max_length=60)),
                ('organism', models.CharField(blank=True, max_length=160)),
                ('bench_notes', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_entries_next', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='lab.laborder')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_releases_next', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_reviews_next', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('legacy', 'Legacy (prior template-based engine)'), ('next', 'Rework (result-type engine)')], default='legacy', help_text="Which lab engine this hospital's queue routes to. A LabSettings row existing does NOT itself mean opted-in — this field is the explicit, single source of truth reception's routing reads. Stays 'legacy' until someone deliberately flips it.", max_length=10)),
                ('phlebotomy_enabled', models.BooleanField(default=False, help_text='Adds a Phlebotomy consultation queue inside the Lab module, ahead of billing.')),
                ('service_entry_mode', models.CharField(choices=[('from_lab', 'From Lab (Phlebotomy intake)'), ('from_reception', 'From Reception (standard)')], default='from_reception', help_text='How new lab visits pick up their tests. Applies to newly created visits only — in-flight visits keep whatever mode they started under.', max_length=20)),
                ('payment_required_before_lab', models.BooleanField(default=False, help_text="If on, the visit balance must be fully settled before reception can send the patient to sample collection. If off (today's behavior), approval alone is enough and credit is allowed.")),
                ('allow_reaccept_before_print', models.BooleanField(default=False, help_text='If on, a released report can be reopened and re-released (e.g. after a correction). If off (default), release locks the results — matches normal LIS discipline.')),
                ('outside_samples_enabled', models.BooleanField(default=True)),
                ('require_review_before_release', models.BooleanField(default=True, help_text='If on, entered results must be explicitly marked reviewed before they can be released.')),
                ('payment_required_before_release', models.BooleanField(default=False, help_text="If on, the visit balance must be fully settled before the report can be released/printed — 'gated on payment for the print itself'. Separate from payment_required_before_lab, which gates sample collection instead.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_settings_next', to='accounts.hospital')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab settings',
                'verbose_name_plural': 'Lab settings',
            },
        ),
        migrations.CreateModel(
            name='DefinedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='lab.labtest')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CultureAntibiotic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_class', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antibiotics', to='lab.labtest')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('value_type', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('coded', 'Coded')], default='numeric', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='lab.labtest')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ParameterRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=6)),
                ('age_min', models.PositiveSmallIntegerField(blank=True, help_text='inclusive, years', null=True)),
                ('age_max', models.PositiveSmallIntegerField(blank=True, help_text='inclusive, years', null=True)),
                ('ref_low', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ref_high', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ref_text', models.CharField(blank=True, max_length=120)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='lab.parameter')),
            ],
            options={
                'ordering': ['sex', 'age_min'],
            },
        ),
        migrations.CreateModel(
            name='ResultValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('group_label', models.CharField(blank=True, max_length=80)),
                ('value_num', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('value_text', models.CharField(blank=True, max_length=255)),
                ('value_code', models.CharField(blank=True, max_length=10)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('ref_display', models.CharField(blank=True, max_length=120)),
                ('flag', models.CharField(blank=True, choices=[('N', 'Normal'), ('H', 'High'), ('L', 'Low'), ('A', 'Abnormal')], max_length=1)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('antibiotic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.cultureantibiotic')),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.parameter')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='lab.labresult')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='labtest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='lab.servicecategory'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='accepted_specimens',
            field=models.ManyToManyField(blank=True, related_name='tests', to='lab.specimentype'),
        ),
    ]
