# Generated by Django 5.2.6 on 2026-09-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0021_labtest_servicecategory_specimentype_laborder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labsettings',
            name='engine',
        ),
    ]
