# Generated by Django 5.2.6 on 2026-09-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0022_remove_labsettings_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimentype',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='specimentype',
            name='is_default',
            field=models.BooleanField(default=False, help_text="System-seeded specimen type. Locked from editing/deletion in the Lab Management screens so the shared catalog can't drift accidentally."),
        ),
    ]
