# Generated by Django 5.2.6 on 2026-09-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0024_seed_default_specimen_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='group_label',
            field=models.CharField(blank=True, help_text='Optional section heading shared by several parameters — e.g. a drug class (Penicillins, Cephalosporins...) on a culture-style panel. Leave blank for a flat panel like a CBC.', max_length=80),
        ),
    ]
