# Generated by Django 5.2.6 on 2026-09-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0025_parameter_group_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value_type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('coded', 'Coded (S / I / R)')], default='numeric', max_length=10),
        ),
    ]
