# Generated by Django 5.2.6 on 2026-09-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0026_alter_parameter_value_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value_type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('coded', 'Coded (S / I / R)'), ('growth', 'Growth / No Growth (dropdown)')], default='numeric', max_length=10),
        ),
    ]
