# Generated by Django 5.2.6 on 2026-09-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0027_alter_parameter_value_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value_type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('coded', 'Coded (S / I / R)'), ('growth', 'Growth / No Growth (dropdown)'), ('level', 'Level (Negative / Trace / 1+ - 4+, dropdown)')], default='numeric', max_length=10),
        ),
    ]
