# Generated by Django 6.0.3 on 2026-09-15 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_organization_alter_user_role_hospital_organization_and_more'),
        ('lab', '0028_alter_parameter_value_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='The hospital that owns this test definition.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='accounts.hospital'),
        ),
    ]
