# Generated by Django 6.0.3 on 2026-09-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0030_alter_labtest_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='is_starter_template',
            field=models.BooleanField(default=False, help_text="Curated by Ternah Health — pinned to the top of every hospital's 'Clone a Test' picker as a ready-made starting point (e.g. a full Culture & Sensitivity panel). Toggle from Django admin only."),
        ),
    ]
