# Generated by Django 6.0.3 on 2026-09-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0033_alter_laborder_visit_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsettings',
            name='combine_defined_option_reports',
            field=models.BooleanField(default=False, help_text="If on, every simple Positive/Negative-style result (Malaria, Typhoid, ...) on a visit prints together on one shared page instead of each getting its own. Parameter-panel tests (CBC, Urinalysis, ...) always keep their own page either way. Off by default, matching today's behavior — every test on its own page."),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='show_report_footnote',
            field=models.BooleanField(default=True, help_text="Shows the standard disclaimer note ('The above results relate only to the specimen submitted...') at the bottom of every printed report. On by default, matching today's behavior — turn off if your hospital doesn't want it printed."),
        ),
    ]
