# Generated by Django 6.0.3 on 2026-04-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('consumables', 'Consumables'), ('maintenance', 'Maintenance'), ('logistics', 'Logistics'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
