# Generated by Django 6.0.3 on 2026-04-23 13:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hospital_box_number_hospital_email_hospital_location_and_more'),
        ('admin_dashboard', '0002_salary_notes_salary_paid_at_alter_expense_category'),
        ('reception', '0006_patient_registration_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='accounts.hospital')),
            ],
            options={
                'ordering': ['bank_name', 'account_name'],
                'unique_together': {('hospital', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='admin_dashboard.bankaccount')),
                ('reconciled_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='reception.payment')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashDrawer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_closing', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discrepancy', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_drawers', to='accounts.hospital')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('cash_in', 'Cash In'), ('cash_out', 'Cash Out')], max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_drawer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='admin_dashboard.cashdrawer')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='reception.payment')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_type', models.CharField(choices=[('bank', 'Bank Reconciliation'), ('three_way', 'Three-Way Reconciliation')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_checks', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposits_in_transit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reconciled_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='admin_dashboard.bankaccount')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_statements', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_statements', to='accounts.hospital')),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MobileMoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_accounts', to='accounts.hospital')),
            ],
            options={
                'ordering': ['provider', 'number'],
                'unique_together': {('hospital', 'number')},
            },
        ),
    ]
