# Generated by Django 6.0.3 on 2026-04-23 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0003_bankaccount_banktransaction_cashdrawer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="source",
            field=models.CharField(
                choices=[
                    ("cash_drawer", "Cash Drawer"),
                    ("bank_account", "Bank Account"),
                    ("mobile_money", "Mobile Money"),
                ],
                default="cash_drawer",
                help_text="Which channel funded this expense",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="notes",
            field=models.TextField(blank=True, help_text="Additional notes about this expense"),
        ),
        migrations.AddField(
            model_name="expense",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="admin_dashboard.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="mobile_money_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="admin_dashboard.mobilemoneyaccount",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="cash_drawer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="admin_dashboard.cashdrawer",
            ),
        ),
    ]
