# Generated by Django 6.0.3 on 2026-04-23 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_expense_account_source_tracking'),
        ('reception', '0006_patient_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationstatement',
            name='mobile_money_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='admin_dashboard.mobilemoneyaccount'),
        ),
        migrations.AlterField(
            model_name='reconciliationstatement',
            name='statement_type',
            field=models.CharField(choices=[('bank', 'Bank Reconciliation'), ('mobile_money', 'Mobile Money Statement'), ('three_way', 'Three-Way Reconciliation')], max_length=20),
        ),
        migrations.CreateModel(
            name='MobileMoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('mobile_money_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='admin_dashboard.mobilemoneyaccount')),
                ('reconciled_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_money_transactions', to='reception.payment')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
    ]
