# Generated by Django 6.0.3 on 2026-04-23 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_reconciliationstatement_mobile_money_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='admin_dashboard.expense'),
        ),
    ]
