# Generated by Django 6.0.3 on 2026-04-27 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_inventoryitem_category_and_more'),
        ('doctor', '0004_prescription'),
        ('reception', '0011_patient_address_patient_date_of_birth_patient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='doctor.prescription'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='reception.visit'),
        ),
    ]
