# Generated by Django 6.0.3 on 2026-04-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_inventorytransaction_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='days_covered_per_pack',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For tubes and other whole-pack items, how many treatment days one pack usually covers.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('drug', 'Tablet / Capsule'), ('syrup', 'Syrup / Suspension'), ('tube', 'Tube / Cream / Ointment'), ('reagent', 'Reagent'), ('sundry', 'Sundry')], default='sundry', max_length=50),
        ),
    ]
