# Generated by Django 6.0.3 on 2026-04-27 16:09

from django.db import migrations, models


def backfill_inventory_units(apps, schema_editor):
    InventoryItem = apps.get_model('admin_dashboard', 'InventoryItem')
    for item in InventoryItem.objects.all():
        updates = {}
        if item.category == 'syrup':
            updates['base_unit'] = 'ml'
            if item.unit == 'unit':
                updates['unit'] = 'bottle'
            if getattr(item, 'pack_size_ml', None):
                updates['units_per_pack'] = item.pack_size_ml
        elif item.category == 'tube':
            if item.base_unit == 'unit':
                updates['base_unit'] = 'g'
            if item.unit == 'unit':
                updates['unit'] = 'tube'
        elif item.category == 'drug':
            if item.base_unit == 'unit':
                updates['base_unit'] = 'tablet'
            if item.unit == 'unit':
                updates['unit'] = 'tablet'
        if updates:
            InventoryItem.objects.filter(pk=item.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_inventoryitem_days_covered_per_pack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='base_unit',
            field=models.CharField(default='unit', help_text='The smallest clinical unit used for prescribing, e.g. tablet, ml, g, vial.', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='strength_mg_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For tablets/capsules, how many mg one unit contains.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='units_per_pack',
            field=models.DecimalField(decimal_places=2, default=1, help_text='How many base units are contained in one stocked/sold pack.', max_digits=10),
        ),
        migrations.RunPython(backfill_inventory_units, migrations.RunPython.noop),
    ]
