# Generated by Django 6.0.3 on 2026-04-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0011_inventorybatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('drug', 'Tablet / Capsule'), ('syrup', 'Syrup / Suspension'), ('iv', 'IV Medication / Fluid'), ('im', 'IM Medication'), ('tube', 'Tube / Cream / Ointment'), ('reagent', 'Reagent'), ('sundry', 'Sundry')], default='sundry', max_length=50),
        ),
    ]
