# Generated by Django 6.0.3 on 2026-05-25 12:32

from django.db import migrations


def lower_drug_reorder_level(apps, schema_editor):
    InventoryItem = apps.get_model("admin_dashboard", "InventoryItem")
    updated = InventoryItem.objects.filter(
        category="drug",
        reorder_level=10,
    ).update(reorder_level=5, low_stock_threshold=5)
    print(f"  Updated {updated} drug item(s): reorder_level 10 -> 5")


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0012_alter_inventoryitem_category'),
    ]

    operations = [
        migrations.RunPython(lower_drug_reorder_level, migrations.RunPython.noop),
    ]
