# Generated by Django 6.0.3 on 2026-06-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0013_fix_drug_reorder_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('consumables', 'Consumables'), ('maintenance', 'Maintenance'), ('logistics', 'Logistics'), ('medicine', 'Medicine'), ('salary', 'Salary'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
