# Generated by Django 6.0.3 on 2026-07-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0016_split_iv_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('drug', 'Tablet / Capsule'), ('syrup', 'Syrup / Suspension'), ('iv_fluid', "IV Fluid (e.g. Normal Saline, Ringer's)"), ('iv_med', 'IV Medication (e.g. Ceftriaxone vial)'), ('im', 'IM Medication'), ('tube', 'Tube / Cream / Ointment'), ('reagent', 'Reagent'), ('sundry', 'Sundry')], default='sundry', max_length=50),
        ),
    ]
