# Generated by Django 6.0.3 on 2026-09-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0017_alter_inventoryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='batch_breakdown',
            field=models.JSONField(blank=True, default=list, help_text="Which batch(es) this CONSUME transaction actually drew from and how much from each -- [{'batch_id', 'batch_number', 'quantity'}, ...]. Lets a later reversal (e.g. undoing a dispensed prescription) credit stock back to the exact original batch/lot instead of a generic new one, preserving that batch's real expiry date."),
        ),
    ]
