# Generated by Django 6.0.3 on 2026-07-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0002_seed_homecare_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecareplacement',
            name='rate_period',
            field=models.CharField(choices=[('session', 'Per Session'), ('day', 'Per Day'), ('placement', 'Per Placement'), ('month', 'Per Month')], default='month', help_text='How often the rates are charged.', max_length=20),
        ),
        migrations.AlterField(
            model_name='homecareplacement',
            name='client_rate',
            field=models.DecimalField(decimal_places=2, help_text='Amount charged to the client (per selected rate period).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='homecareplacement',
            name='nurse_rate',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid to the nurse (per selected rate period).', max_digits=12),
        ),
    ]
