# Generated by Django 6.0.3 on 2026-07-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0003_add_rate_period_to_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecareplacement',
            name='rate_period',
            field=models.CharField(choices=[('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month')], default='month', help_text='How often the rates are charged.', max_length=20),
        ),
    ]
