from django.urls import path

from . import views

urlpatterns = [
    path("superadmin/", views.developer_dashboard, name="developer_dashboard"),
    path("superadmin/hospitals/", views.manage_hospitals, name="manage_hospitals"),
    path("superadmin/hospitals/<int:hospital_id>/edit/", views.edit_hospital, name="edit_hospital"),
    path("superadmin/hospitals/<int:hospital_id>/delete/", views.delete_hospital, name="delete_hospital"),
    path("superadmin/subscription-plans/", views.manage_subscription_plans, name="manage_subscription_plans"),
    path("superadmin/subscription-plans/<int:plan_id>/edit/", views.edit_subscription_plan, name="edit_subscription_plan"),
    path("superadmin/subscription-plans/<int:plan_id>/delete/", views.delete_subscription_plan, name="delete_subscription_plan"),
    path("superadmin/subscription-payments/", views.manage_subscription_payments, name="manage_subscription_payments"),
    path("superadmin/subscription-payments/<int:payment_id>/edit/", views.edit_subscription_payment, name="edit_subscription_payment"),
    path("superadmin/subscription-payments/<int:payment_id>/delete/", views.delete_subscription_payment, name="delete_subscription_payment"),
    path("superadmin/audit-logs/", views.view_audit_logs, name="view_audit_logs"),
    path("hospital/", views.hospital_dashboard, name="hospital_dashboard"),
    path("hospital/financials/", views.financial_report, name="financial_report"),
    path("hospital/financials/statements/", views.financial_statements, name="financial_statements"),
    path("hospital/financials/metrics/<slug:metric>/", views.financial_metric_detail, name="financial_metric_detail"),
    path("hospital/financials/bank-accounts/", views.bank_account_list, name="bank_account_list"),
    path("hospital/financials/bank-accounts/add/", views.bank_account_create, name="bank_account_create"),
    path("hospital/financials/bank-accounts/<int:account_id>/", views.bank_account_detail, name="bank_account_detail"),
    path("hospital/financials/bank-accounts/<int:account_id>/edit/", views.edit_bank_account, name="edit_bank_account"),
    path("hospital/financials/bank-accounts/<int:account_id>/delete/", views.delete_bank_account, name="delete_bank_account"),
    path("hospital/financials/mobile-money/", views.mobile_money_list, name="mobile_money_list"),
    path("hospital/financials/mobile-money/add/", views.mobile_money_create, name="mobile_money_create"),
    path("hospital/financials/mobile-money/<int:account_id>/", views.mobile_money_account_detail, name="mobile_money_account_detail"),
    path("hospital/financials/mobile-money/<int:account_id>/edit/", views.edit_mobile_money, name="edit_mobile_money"),
    path("hospital/financials/mobile-money/<int:account_id>/delete/", views.delete_mobile_money, name="delete_mobile_money"),
    # Cash drawer is now represented as a daily cash statement inside Financial Statements.
    path("hospital/financials/receipts/", views.receipts_list, name="receipts_list"),
    path("hospital/financials/bank-reconciliation/", views.bank_reconciliation, name="bank_reconciliation"),
    path("hospital/financials/bank-statements/", views.bank_reconciliation, name="bank_statements"),
    path("hospital/financials/mobile-money-statement/", views.mobile_money_statement, name="mobile_money_statement"),
    path("hospital/financials/three-way-reconciliation/", views.three_way_reconciliation, name="three_way_reconciliation"),
    path("hospital/financials/reconciliation/<int:pk>/", views.reconciliation_detail, name="reconciliation_detail"),
    path("hospital/users/", views.manage_users, name="manage_users"),
    path("hospital/users/<int:user_id>/edit/", views.edit_user, name="edit_user"),
    path("hospital/users/<int:user_id>/deactivate/", views.deactivate_user, name="deactivate_user"),
    path("hospital/services/", views.manage_services, name="manage_services"),
    path("hospital/services/<int:service_id>/edit/", views.edit_service, name="edit_service"),
    path("hospital/services/<int:service_id>/delete/", views.delete_service, name="delete_service"),
    path("hospital/expenses/", views.manage_expenses, name="manage_expenses"),
    path("hospital/expenses/<int:expense_id>/edit/", views.edit_expense, name="edit_expense"),
    path("hospital/expenses/<int:expense_id>/delete/", views.delete_expense, name="delete_expense"),
    path("hospital/salaries/", views.manage_salaries, name="manage_salaries"),
    path("hospital/salaries/<int:salary_id>/edit/", views.edit_salary, name="edit_salary"),
    path("hospital/salaries/<int:salary_id>/delete/", views.delete_salary, name="delete_salary"),
    path("hospital/inventory/", views.manage_inventory, name="manage_inventory"),
    path("hospital/inventory/report/", views.download_inventory_report, name="download_inventory_report"),
    path("hospital/inventory/report/print/", views.printable_inventory_report, name="printable_inventory_report"),
    path("hospital/inventory/report/xlsx/", views.download_inventory_xlsx, name="download_inventory_xlsx"),
    path("hospital/inventory/<int:item_id>/restock/", views.restock_inventory_item, name="restock_inventory_item"),
    path("hospital/inventory/<int:item_id>/edit/", views.edit_inventory_item, name="edit_inventory_item"),
    path("hospital/inventory/<int:item_id>/delete/", views.delete_inventory_item, name="delete_inventory_item"),
]
