# Generated by Django 6.0.3 on 2026-04-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='box_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hospital',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hospital',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hospital',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_logos/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
