# Generated by ChatGPT on 2026-04-25

from django.db import migrations


def create_groups_and_assign_users(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("accounts", "User")

    group_names = ["Reception", "Lab", "Doctor", "Nurse"]
    groups = {}
    for name in group_names:
        group, _ = Group.objects.get_or_create(name=name)
        groups[name] = group

    # Backward compatible: map single-role users into their default group.
    role_to_group = {
        "receptionist": "Reception",
        "lab_attendant": "Lab",
        "doctor": "Doctor",
        "nurse": "Nurse",
    }

    for user in User.objects.all().iterator():
        group_name = role_to_group.get(getattr(user, "role", "") or "")
        if not group_name:
            continue
        try:
            user.groups.add(groups[group_name])
        except Exception:
            # Some custom user implementations may not expose groups; ignore safely.
            continue


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_hospital_box_number_hospital_email_hospital_location_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(create_groups_and_assign_users, migrations.RunPython.noop),
    ]

