# Generated by Django 6.0.3 on 2026-06-23 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_default_module_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_core', models.BooleanField(default=False, help_text='Core modules (e.g. Reception) are included with every hospital and cannot be unselected.')),
                ('url_name', models.CharField(blank=True, help_text="Django URL name for this module's sidebar entry.", max_length=100)),
                ('icon_svg', models.TextField(blank=True, help_text='Inner SVG path markup for the sidebar icon.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalModuleSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_subscriptions', to='accounts.hospital')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_subscriptions', to='accounts.module')),
            ],
            options={
                'ordering': ['module__display_order'],
                'unique_together': {('hospital', 'module')},
            },
        ),
    ]
