# Generated by Django 6.0.3 on 2026-07-14 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_system_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='reactivation_alert_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Days before expiry to start showing the reactivation alert. Set to 0 to disable.'),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Leave blank to broadcast to every hospital.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_notifications', to='accounts.hospital'),
        ),
        migrations.CreateModel(
            name='InternalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notifications', to='accounts.hospital')),
                ('recipient', models.ForeignKey(blank=True, help_text='Leave blank to send to all staff in this hospital.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_internal_notifications', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_internal_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalNotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='accounts.internalnotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notification_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('notification', 'user')},
            },
        ),
    ]
