# Generated by Django 6.0.3 on 2026-07-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_direct_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_enabled', models.BooleanField(default=True, help_text='Super-admin can send broadcast notifications to hospitals.')),
                ('internal_messages_enabled', models.BooleanField(default=True, help_text='Hospital admins can send internal announcements to their staff.')),
                ('direct_messages_enabled', models.BooleanField(default=True, help_text='Staff members can send private messages to each other.')),
                ('message_retention_days', models.PositiveSmallIntegerField(default=7, help_text='Days before messages and notifications are automatically purged. 0 = never purge.')),
            ],
            options={
                'verbose_name': 'Platform Settings',
            },
        ),
    ]
