# Generated by Django 6.0.3 on 2026-08-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_role_max_length_50'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('hospital_admin', 'Hospital Admin'), ('accountant', 'Accountant'), ('receptionist', 'Receptionist'), ('lab_attendant', 'Lab Attendant'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('sonographer', 'Sonographer')], default='lab_attendant', max_length=20),
        ),
    ]
