# Generated by Django 5.2.6 on 2026-09-14 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_seed_ternah_books_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('owner', 'Owner (multi-branch)'), ('hospital_admin', 'Hospital Admin'), ('accountant', 'Accountant'), ('receptionist', 'Receptionist'), ('lab_attendant', 'Lab Attendant'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('sonographer', 'Sonographer')], default='lab_attendant', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Optional — group this branch under an Organization so its owner can see it alongside sibling branches. Leave blank for a standalone hospital.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Set for ROLE_OWNER users only — the group of branches this account can see. Not scoped to a single Hospital the way every other role is.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to='accounts.organization'),
        ),
    ]
