# Generated by Django 6.0.3 on 2026-09-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_organization_alter_user_role_hospital_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='report_code',
            field=models.CharField(blank=True, default="", help_text="Short code used on printed reports and patient/visit numbers instead of the full subdomain (e.g. 'LMS'). Leave blank to auto-abbreviate the hospital name.", max_length=12),
        ),
    ]
