# Generated by Django 6.0.3 on 2026-09-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_hospital_report_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='doctor_wait_warn_minutes',
            field=models.PositiveSmallIntegerField(db_default=30, default=30, help_text='Home screen: flag the Doctor tile once the longest-waiting patient passes this many minutes.'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='lab_pending_warn_minutes',
            field=models.PositiveSmallIntegerField(db_default=120, default=120, help_text='Home screen: flag the Laboratory tile once the oldest pending result passes this many minutes.'),
        ),
    ]
