# Generated by Django 6.0.3 on 2026-09-05 11:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('role', models.CharField(blank=True, choices=[('ar', 'Accounts receivable'), ('ap', 'Accounts payable'), ('wht', 'Withholding tax receivable'), ('vat', 'VAT payable'), ('deferred', 'Deferred revenue'), ('credits', 'Customer credits'), ('bank', 'Bank'), ('cash', 'Cash'), ('momo_mtn', 'MoMo MTN'), ('momo_airtel', 'MoMo Airtel'), ('director', "Director's current account"), ('retained', 'Retained earnings'), ('fx', 'FX gain/loss'), ('charges', 'Bank/MoMo transaction charges')], max_length=20)),
                ('is_deductible', models.BooleanField(default=True)),
                ('is_direct_cost', models.BooleanField(default=False)),
                ('is_payment_account', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trading_name', models.CharField(blank=True, max_length=200)),
                ('tin', models.CharField(blank=True, max_length=30)),
                ('is_withholding_agent', models.BooleanField(default=False, help_text='URA-designated agents withhold 6% and remit it directly to URA on your behalf.')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('payment_terms_days', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('trading_name', models.CharField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('tin', models.CharField(blank=True, max_length=30)),
                ('vrn', models.CharField(blank=True, max_length=30, verbose_name='VAT registration number')),
                ('company_reg_no', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='books/logo/')),
                ('brand_colour', models.CharField(blank=True, help_text='Hex colour, e.g. #2f4cff', max_length=7)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('momo_mtn_number', models.CharField(blank=True, max_length=30)),
                ('momo_mtn_name', models.CharField(blank=True, max_length=150)),
                ('momo_airtel_number', models.CharField(blank=True, max_length=30)),
                ('momo_airtel_name', models.CharField(blank=True, max_length=150)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('receipt_prefix', models.CharField(default='RCT', max_length=10)),
                ('credit_note_prefix', models.CharField(default='CN', max_length=10)),
                ('default_payment_terms_days', models.PositiveIntegerField(default=14)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('invoice_footer_notes', models.TextField(blank=True)),
                ('receipt_footer_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('source_type', models.CharField(choices=[('invoice', 'Invoice'), ('payment', 'Payment'), ('expense', 'Expense'), ('wht', 'Withholding credit'), ('manual', 'Manual entry')], max_length=20)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_posted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='books.financialyear')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='books.journalentry')),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=10)),
                ('kind', models.CharField(choices=[('onboarding', 'Onboarding'), ('subscription', 'Subscription'), ('project', 'Project'), ('retainer', 'Retainer'), ('other', 'Other')], default='other', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('apply_vat', models.BooleanField(default=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='books.client')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='books.journalentry')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fx_rate', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12)),
                ('amount_ugx', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('momo_mtn', 'MoMo (MTN)'), ('momo_airtel', 'MoMo (Airtel)'), ('card', 'Card'), ('other', 'Other')], default='bank', max_length=20)),
                ('paid_personally', models.BooleanField(default=False, help_text="Paid by the director personally — the company owes this back via the director's current account.")),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('transaction_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='books/receipts/')),
                ('receipt_hash', models.CharField(blank=True, max_length=64)),
                ('no_receipt_reason', models.CharField(blank=True, max_length=255)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('is_deductible', models.BooleanField(default=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='books.account')),
                ('paid_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_paid_from', to='books.account')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='books.journalentry')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='books.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='books.journalentry')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('momo_mtn', 'MoMo (MTN)'), ('momo_airtel', 'MoMo (Airtel)'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='books.client')),
                ('deposit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_deposited', to='books.account')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='books.journalentry')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='books.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='books.invoice')),
                ('revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='books.account')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='books.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('prefix', models.CharField(max_length=20)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('padding', models.PositiveSmallIntegerField(default=4)),
            ],
            options={
                'unique_together': {('key', 'year')},
            },
        ),
        migrations.CreateModel(
            name='WithholdingCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='books/wht_certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withholding_credits', to='books.client')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withholding_credits', to='books.invoice')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withholding_credit', to='books.journalentry')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withholding_credits', to='books.payment')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='books.invoice')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('invoice', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='books.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='books.payment')),
            ],
            options={
                'unique_together': {('payment', 'invoice')},
            },
        ),
    ]
