# Generated by Django 6.0.3 on 2026-09-05 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_seed_ternah_books_tenant'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hospital',
            field=models.OneToOneField(blank=True, help_text="Link to the tenant row if this client runs one of our products. Blank for website builds and one-off project clients that aren't tenants.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_client', to='accounts.hospital'),
        ),
    ]
