# Generated by Django 5.2.6 on 2026-09-07 08:58

from django.db import migrations, models


def blank_to_null(apps, schema_editor):
    """Existing rows with number='' / receipt_number='' would collide under the
    new unique constraint below (SQL treats '' as a real, comparable value —
    only NULL is exempt from a unique check). These are stuck/broken draft
    invoices that never issued; NULL is what the model now uses for "no
    number yet", so normalize before the constraint is added."""
    Invoice = apps.get_model('books', 'Invoice')
    Invoice.objects.filter(number='').update(number=None)
    Payment = apps.get_model('books', 'Payment')
    Payment.objects.filter(receipt_number='').update(receipt_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_client_hospital'),
    ]

    operations = [
        # Step 1: allow NULL first (still not unique yet) so the data cleanup
        # below has somewhere to put "no number assigned" values.
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        # Step 2: normalize existing '' rows to NULL — '' is a real, comparable
        # value under a unique constraint (only NULL is exempt), so any stuck
        # blank drafts/payments sharing '' would otherwise block step 3.
        migrations.RunPython(blank_to_null, migrations.RunPython.noop),
        # Step 3: now safe to enforce uniqueness.
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, unique=True),
        ),
    ]
