# Generated by Django 6.0.3 on 2026-10-02 09:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_invoice_number_alter_payment_receipt_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date')], default='text', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='TSC', help_text='First part of the number, e.g. TSC in TSC-SACCO-2026-001.', max_length=10)),
                ('validity_days', models.PositiveIntegerField(default=30, help_text='Default days until a quotation expires.')),
                ('intro', models.TextField(blank=True, default='Thank you for choosing Ternah. The quotation below covers a complete deployment, configured to your needs and supported through go-live.')),
                ('note_left_title', models.CharField(blank=True, default='What the price reflects', max_length=80)),
                ('note_left_body', models.TextField(blank=True)),
                ('note_right_title', models.CharField(blank=True, default='Payment & travel', max_length=80)),
                ('note_right_body', models.TextField(blank=True)),
                ('footer_tagline', models.CharField(blank=True, default='Keep it simple.', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Middle part of the number, e.g. SACCO in TSC-SACCO-2026-001.', max_length=10)),
                ('number', models.CharField(blank=True, default=None, max_length=40, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('converted', 'Invoiced')], default='draft', max_length=10)),
                ('subtitle', models.CharField(blank=True, help_text='Shown under QUOTATION, e.g. SACCO Management System.', max_length=120)),
                ('attention', models.CharField(blank=True, help_text='e.g. The Chairperson / Manager', max_length=120)),
                ('location', models.CharField(blank=True, help_text='e.g. Kajjansi, Uganda', max_length=120)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('intro', models.TextField(blank=True)),
                ('apply_vat', models.BooleanField(default=False)),
                ('highlight_title', models.CharField(blank=True, help_text='Optional green box, e.g. This setup comes with 3 months of FREE hosting.', max_length=120)),
                ('highlight_body', models.CharField(blank=True, max_length=255)),
                ('note_left_title', models.CharField(blank=True, max_length=80)),
                ('note_left_body', models.TextField(blank=True)),
                ('note_right_title', models.CharField(blank=True, max_length=80)),
                ('note_right_body', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='books.client')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation', to='books.invoice')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('basis', models.CharField(blank=True, help_text='e.g. One-time, 3 days x 150,000', max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='books.quotation')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='books.quotationfield')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='books.quotation')),
            ],
            options={
                'unique_together': {('quotation', 'field')},
            },
        ),
    ]
