# Generated by Django 6.0.3 on 2026-10-04 21:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_quotations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='books.account')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Shown on each invoice, e.g. Hosting & maintenance', max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('next_run_date', models.DateField(help_text='Date of the next invoice, e.g. the day the free period ends.')),
                ('end_date', models.DateField(blank=True, help_text='Optional last billing date.', null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoices', to='books.client')),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoices', to='books.account')),
            ],
            options={
                'ordering': ['next_run_date', 'id'],
            },
        ),
    ]
