# Generated by Django 6.0.3 on 2026-10-04 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reception', '0031_service_specialty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRefraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_refraction', to='reception.visit')),
            ],
        ),
        migrations.CreateModel(
            name='EyeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_right', models.TextField(blank=True)),
                ('external_left', models.TextField(blank=True)),
                ('slit_lamp', models.JSONField(blank=True, default=dict)),
                ('cdr_right', models.CharField(blank=True, max_length=20)),
                ('cdr_left', models.CharField(blank=True, max_length=20)),
                ('iop_right', models.CharField(blank=True, max_length=20)),
                ('iop_left', models.CharField(blank=True, max_length=20)),
                ('diagnoses', models.JSONField(blank=True, default=list)),
                ('history_comments', models.TextField(blank=True)),
                ('management_plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eye_exam', to='reception.visit')),
            ],
        ),
    ]
