"""
Django settings for labsystem project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import importlib.util
import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured


BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent


def env(key, default=None):
    return os.getenv(key, default)


def env_bool(key, default=False):
    value = os.getenv(key)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(key, default=""):
    raw = os.getenv(key, default)
    if isinstance(raw, (list, tuple)):
        return [item for item in raw if item]
    return [item.strip() for item in str(raw).split(",") if item.strip()]


def database_config():
    database_url = env("DATABASE_URL")
    if database_url:
        database_url = database_url.strip()
        # Be forgiving with common App Platform/UI paste formats, such as:
        # - quoted values: "postgresql://..."
        # - assignment values pasted into a single value field: DATABASE_URL=...
        # - export commands copied from a shell: export DATABASE_URL=...
        while True:
            normalized = database_url
            if len(normalized) >= 2 and normalized[0] == normalized[-1] and normalized[0] in {"'", '"'}:
                normalized = normalized[1:-1].strip()
            if normalized.lower().startswith("export database_url="):
                normalized = normalized.split("=", 1)[1].strip()
            elif normalized.lower().startswith("database_url="):
                normalized = normalized.split("=", 1)[1].strip()
            if normalized == database_url:
                break
            database_url = normalized
    if not database_url:
        return {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "OPTIONS": {
                # Avoid "database is locked" during local dev when requests overlap.
                "timeout": int(env("SQLITE_TIMEOUT", "30")),
            },
        }
    # App Platform can leave unresolved bindable placeholders like ${db.DATABASE_URL}
    # during builds or when the backing resource is missing. Fall back to SQLite
    # instead of crashing settings import.
    if database_url.startswith("${") and database_url.endswith("}"):
        return {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "OPTIONS": {
                "timeout": int(env("SQLITE_TIMEOUT", "30")),
            },
        }
    try:
        return dj_database_url.parse(
            database_url,
            conn_max_age=int(env("DB_CONN_MAX_AGE", "600")),
            ssl_require=True,
        )
    except Exception as exc:
        raise ImproperlyConfigured(f"Invalid DATABASE_URL configuration: {exc}") from exc


default_dev_secret = "django-insecure-s8c3k38(z(z4z388vh@(z35foyi39o%-4_pe-@-x@d1p#7(0hz"
SECRET_KEY = env("DJANGO_SECRET_KEY", default_dev_secret)

DEBUG = env_bool("DJANGO_DEBUG", True)

if not DEBUG and SECRET_KEY == default_dev_secret:
    raise ImproperlyConfigured(
        "Set DJANGO_SECRET_KEY before running in production."
    )


ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    "127.0.0.1,localhost,testserver",
)

CSRF_TRUSTED_ORIGINS = env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "",
)
CSRF_FAILURE_VIEW = "accounts.views.csrf_failure"


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "admin_dashboard",
    "doctor",
    "lab",
    "nurse",
    "reception",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "labsystem.middleware.SessionIdleTimeoutMiddleware",
    "labsystem.middleware.HospitalMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if importlib.util.find_spec("whitenoise") is not None:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = "labsystem.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "labsystem.wsgi.application"
ASGI_APPLICATION = "labsystem.asgi.application"


DATABASES = {
    "default": database_config(),
}


AUTH_USER_MODEL = "accounts.User"


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

project_static_dir = PROJECT_ROOT / "static"
STATICFILES_DIRS = [project_static_dir] if project_static_dir.exists() else []

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Use WhiteNoise manifest storage only in production-like environments.
# In DEBUG/tests we avoid the manifest requirement so templates can render without collectstatic.
if importlib.util.find_spec("whitenoise") is not None and not DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }


LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "app_home"  # Role-based router that checks user role
LOGOUT_REDIRECT_URL = "login"
SESSION_IDLE_TIMEOUT_SECONDS = int(env("DJANGO_SESSION_IDLE_TIMEOUT_SECONDS", "1800"))
SESSION_COOKIE_AGE = SESSION_IDLE_TIMEOUT_SECONDS
SESSION_SAVE_EVERY_REQUEST = True


SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = env("DJANGO_SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = env("DJANGO_CSRF_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_HTTPONLY = env_bool("DJANGO_CSRF_COOKIE_HTTPONLY", False)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
SECURE_HSTS_SECONDS = int(env("DJANGO_SECURE_HSTS_SECONDS", "0" if DEBUG else "3600"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    not DEBUG,
)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
