"""
Django settings for labsystem project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import importlib.util
import os
import shlex
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

from django.core.exceptions import ImproperlyConfigured


BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent


def env(key, default=None):
    return os.getenv(key, default)


def env_bool(key, default=False):
    value = os.getenv(key)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(key, default=""):
    raw = os.getenv(key, default)
    if isinstance(raw, (list, tuple)):
        return [item for item in raw if item]
    return [item.strip() for item in str(raw).split(",") if item.strip()]


def database_config():
    database_url = env("DATABASE_URL")
    if database_url:
        database_url = database_url.strip()
    if not database_url:
        return {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    # App Platform can leave unresolved bindable placeholders like ${db.DATABASE_URL}
    # during builds or when the backing resource is missing. Fall back to SQLite
    # instead of crashing settings import.
    if database_url.startswith("${") and database_url.endswith("}"):
        return {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }

    parsed = urlparse(database_url)
    scheme = parsed.scheme.lower()
    conn_max_age = int(env("DB_CONN_MAX_AGE", "60"))
    query_options = {
        key: values[-1]
        for key, values in parse_qs(parsed.query).items()
        if values and values[-1]
    }

    def postgres_config(name="", user="", password="", host="", port="", extra_options=None):
        config = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": name,
            "USER": user,
            "PASSWORD": password,
            "HOST": host,
            "PORT": str(port or ""),
            "CONN_MAX_AGE": conn_max_age,
            "CONN_HEALTH_CHECKS": True,
        }
        options = {}
        for option_key in ("sslmode", "sslrootcert", "sslcert", "sslkey", "target_session_attrs"):
            option_value = (extra_options or {}).get(option_key)
            if option_value:
                options[option_key] = option_value
        if options:
            config["OPTIONS"] = options
        return config

    if scheme in {"postgres", "postgresql", "pgsql"}:
        return postgres_config(
            name=unquote(parsed.path.lstrip("/")),
            user=unquote(parsed.username or ""),
            password=unquote(parsed.password or ""),
            host=parsed.hostname or "",
            port=parsed.port or "",
            extra_options=query_options,
        )

    if scheme == "sqlite":
        db_name = unquote(parsed.path.lstrip("/")) or "db.sqlite3"
        return {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / db_name,
        }

    # Some platforms surface PostgreSQL credentials as a libpq-style DSN such as:
    # "host=... port=25060 user=... password=... dbname=... sslmode=require".
    # Support that shape as well so builds do not fail on a non-URL DATABASE_URL.
    if "=" in database_url and "://" not in database_url:
        dsn_parts = {}
        for chunk in shlex.split(database_url):
            if "=" not in chunk:
                continue
            key, value = chunk.split("=", 1)
            dsn_parts[key.strip().lower()] = value.strip()

        if dsn_parts:
            name = (
                dsn_parts.get("dbname")
                or dsn_parts.get("database")
                or dsn_parts.get("name")
                or ""
            )
            user = dsn_parts.get("user") or dsn_parts.get("username") or ""
            if name and user:
                return postgres_config(
                    name=name,
                    user=user,
                    password=dsn_parts.get("password", ""),
                    host=dsn_parts.get("host", ""),
                    port=dsn_parts.get("port", ""),
                    extra_options=dsn_parts,
                )

    raise ImproperlyConfigured(
        "Unsupported DATABASE_URL scheme. Use postgres/postgresql/sqlite or a libpq-style Postgres DSN."
    )


default_dev_secret = "django-insecure-s8c3k38(z(z4z388vh@(z35foyi39o%-4_pe-@-x@d1p#7(0hz"
SECRET_KEY = env("DJANGO_SECRET_KEY", default_dev_secret)

DEBUG = env_bool("DJANGO_DEBUG", True)

if not DEBUG and SECRET_KEY == default_dev_secret:
    raise ImproperlyConfigured(
        "Set DJANGO_SECRET_KEY before running in production."
    )


ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    "127.0.0.1,localhost",
)

CSRF_TRUSTED_ORIGINS = env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "",
)


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "lab",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if importlib.util.find_spec("whitenoise") is not None:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = "labsystem.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "labsystem.wsgi.application"
ASGI_APPLICATION = "labsystem.asgi.application"


DATABASES = {
    "default": database_config(),
}


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

project_static_dir = PROJECT_ROOT / "static"
STATICFILES_DIRS = [project_static_dir] if project_static_dir.exists() else []

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

if importlib.util.find_spec("whitenoise") is not None:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }


LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "report_list"
LOGOUT_REDIRECT_URL = "login"


SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
SECURE_HSTS_SECONDS = int(env("DJANGO_SECURE_HSTS_SECONDS", "0" if DEBUG else "3600"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    not DEBUG,
)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
